Create example slash command and unit test
Ziggiyzoo/BRVNS-Discord-Bot pull request #6
Opened 2022-07-21 16:26 UTC by Ziggiyzoo

Created a slash command, in the Bot API and then corresponding logic in Bot Logic. Added a test for the logic

2022-07-22 01:33 UTC, Renegade-Master commented on src/brvns_config.py
> +    config.read("~/../config/ConfigFile.ini")
We shouldn't be reading files from the home directory really. That seems unnecessary.

2022-07-22 01:35 UTC, Renegade-Master commented on src/brvns_bot_logic.py
> +    def add_extra_public_method(self):
🤔

2022-07-22 01:36 UTC, Renegade-Master commented on .github/workflows/verify_commit.yml
> +          poetry run -m pytest
Why have you changed this?

2022-07-22 01:38 UTC, Renegade-Master commented on .github/workflows/verify_commit.yml
> +          poetry run python -m pytest
Why are you running PyTest from Python now?

2022-07-22 01:41 UTC, Ziggiyzoo commented on src/brvns_config.py
> +    config.read("~/../config/ConfigFile.ini")
Where should I put it? Would putting it in src make more sense?

2022-07-22 01:42 UTC, Ziggiyzoo commented on .github/workflows/verify_commit.yml
> +          poetry run -m pytest
`poetry run pytest` leads to: `modules src does not exist`

2022-07-22 01:43 UTC, Renegade-Master commented on src/brvns_config.py
> +    def set_config(self):
If this isn't necessary, then it probably shouldn't exist.

2022-07-22 01:44 UTC, Ziggiyzoo commented on src/brvns_config.py
> +    def set_config(self):
Then how should I get it to pass pylint which requires a class to have 2 public methods?..

2022-07-22 01:44 UTC, Renegade-Master commented on src/brvns_config.py
> +    config.read("~/../config/ConfigFile.ini")
Yeah, well a resources-type directory in the repo at least.

2022-07-22 01:45 UTC, Renegade-Master commented on .github/workflows/verify_commit.yml
> +          poetry run -m pytest
Then we make it exist. That sounds like a problem with the code.

2022-07-22 01:57 UTC, Renegade-Master commented on .github/workflows/verify_commit.yml
> +          poetry run python -m pytest
Pretty sure the following should work
```python
PYTHONPATH="$(pwd):$PYTHONPATH" poetry run pytest
```

2022-07-22 01:58 UTC, Renegade-Master commented on config/ConfigFile.ini
> +string.signup_string = "To signup to the Blue Ravens Org, visit: https://robertsspaceindustries.com/orgs/BRVNS."
If all of these are going to be Strings, they probably don't need to start with `string`.

2022-07-22 02:01 UTC, Renegade-Master commented on src/brvns_config.py
> +    def set_config(self):
Same as above: If it currently doesn't need more than one method, then it should be a static method, not a class.

2022-07-22 02:45 UTC, Ziggiyzoo commented on src/brvns_bot_logic.py
> +    def add_extra_public_method(self):
There will be extra in here.. I just couldn't think of another command to add x)

2022-07-22 03:06 UTC, Ziggiyzoo commented
OK - All tests have passed. 

However, when running the bot itself, brvns_bot_api throws errors with the methods saying that:

`TypeError: on_ready() missing 1 required positional argument: 'self'`

I think this is because the object of it is not instantiated properly in main.py

2022-07-22 14:23 UTC, Renegade-Master commented on src/brvns_bot_logic.py
> +    def add_extra_public_method(self):
A better thing to do then would be to disable the rule temporarily for this class.

```diff
-class BrvnsLogic():
-    """
-    BRVNS Bot Logic
-    """
-    brvns_config = BrvnsResources()
-
-    def signup_string(self, author_name):
-        """
-        Return signup string
-        """
-        message_content = self.brvns_config.get_config("STRINGS", "signup_string")
-        signup_string = f'Hello {author_name}. {message_content}'
-        return str(signup_string)
-    def add_extra_public_method(self):
-        """
-        Satisfy pylints desire for control
-        """
-        return "We love you pylint"

+# pylint: disable=too-few-public-methods
+class BrvnsLogic():
+    """
+    BRVNS Bot Logic
+    """
+    brvns_config = BrvnsResources()
+
+    def signup_string(self, author_name):
+        """
+        Return signup string
+        """
+        message_content = self.brvns_config.get_config("STRINGS", "signup_string")
+        signup_string = f'Hello {author_name}. {message_content}'
+        return str(signup_string)    
    
```

2022-07-22 15:02 UTC, Renegade-Master commented on src/brvns_resources.py
> +        self.config.set(section, key, value)
This could probably be reduced to just some static methods. Not sure what the advantage of an entire Class is here.

```suggestion
"""
BRVNS Config Utilities
"""

import configparser
import os

"""
Brvns Config

Currently this is going to a harcoded file in the project.
Though it should talk to a DB, this will allow admins to set
their own responses.. I will need to look up how to properly
create a DB connection etc..
"""
config = configparser.ConfigParser()

thisfolder = os.path.dirname(os.path.abspath(__file__))
inifile = os.path.join(thisfolder, "resources/resources.ini")
config.read(inifile)

def get_config(self, section, key):
    """
    Get the config from the .ini file
    """
    return self.config.get(section, key)

# Allow discord mod to create their own hardcoded
# This needs to actually check if it was successful. I cannot be
# bothered to add a test for it not. Do this tomorrow david
def set_config(self, section, key, value):
    """
    Sets a section and key in resources.ini
    """
    self.config.set(section, key, value)

```

2022-07-24 16:23 UTC, Renegade-Master commented on src/__init__.py
> +Module docstring
```suggestion
BRVNS Source Module
```

2022-07-24 16:24 UTC, Renegade-Master commented on src/brvns_bot.py
> +# pylint: disable=too-many-ancestors
What is this about? What is the complaint?

2022-07-24 16:25 UTC, Renegade-Master commented on src/cogs/slash_brvns.py
> +def setup(bot):
Why is this method outside of the Class?

2022-07-24 16:26 UTC, Renegade-Master commented on src/cogs/slash_general.py
> +    bot.add_cog(SlashGeneral(bot))
Why is this method outside of the Class? It references Class internals, so why should it not be a part of the Class?

2022-07-24 16:26 UTC, Renegade-Master commented on src/cogs/slash_brvns.py
> +    bot.add_cog(SlashBrvns(bot))
Why is this method outside of the Class? It references Class internals, so why should it not be a part of the Class?

2022-07-24 16:29 UTC, Renegade-Master commented on src/resources/resources.ini
> +string.string_test = This is the test string.
Really, Test Strings should probably be in their own Test Strings file, rather than lumped in with the main Strings.

2022-07-24 16:31 UTC, Renegade-Master requested changes
Some small things to change, but seems to be nearly complete. I'm not entirely sure about the structure of all the Classes regarding ease of testing, but it is nothing (at this stage) a refactor couldn't fix.

2022-07-24 16:34 UTC, Renegade-Master commented
I did made a commit here, so you will need to update your local branch, @Ziggiyzoo 

```shell
git fetch -a

git pull origin Create-example-slash-command-and-unit-test --rebase --ff-only
```

2022-07-24 17:05 UTC, Renegade-Master commented on src/cogs/slash_brvns.py
> +    bot.add_cog(SlashBrvns(bot))
This should probably be done during the creation of the `bot` object that is passed in.

2022-07-24 17:08 UTC, Renegade-Master commented on src/brvns_bot.py
> +        print("Cogs added.")
Is there any instance where you would want to create the Bot, but not initialise the Cogs? If not, this should probably go in the `__init__` function.

2022-07-24 17:36 UTC, Ziggiyzoo reviewed
Bot is working, tests passing, pylint satisfied.

Any final changes to request?

2022-07-24 17:54 UTC, Renegade-Master approved these changes
Looks good enough to me 👍

2022-07-24 17:59 UTC, merged